name: 'ai_analytics_lab'
version: '1.0'
config-version: 2

profile: 'ai_analytics_lab'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  ai_analytics_lab:
    staging:
      +materialized: view
    marts:
      +materialized: table